type Sample = { at: number; value: number };
type Cycle = { completedAt:string|null; source:string; providerQueueMs:number; providerResponseMs:number; processingMs:number; redisPublishMs:number; sseSendMs:number; internalLatencyMs:number; providerDelayMs:number; endToEndMeasuredMs:number; fixtures:number };
const stages = new Map<string, Sample[]>();
let currentProvider = { queueMs:0, responseMs:0, source:"unknown" };
let latest: Cycle = { completedAt:null,source:"waiting",providerQueueMs:0,providerResponseMs:0,processingMs:0,redisPublishMs:0,sseSendMs:0,internalLatencyMs:0,providerDelayMs:0,endToEndMeasuredMs:0,fixtures:0 };
function add(stage:string,value:number){const rows=stages.get(stage)??[];rows.push({at:Date.now(),value:Math.max(0,value)});const cutoff=Date.now()-3600000;while(rows[0]&&rows[0].at<cutoff)rows.shift();if(rows.length>600)rows.shift();stages.set(stage,rows);}
export function recordLiveProvider(queueMs:number,responseMs:number,source="api-football"){currentProvider={queueMs,responseMs,source};add("providerQueueMs",queueMs);add("providerResponseMs",responseMs);}
export function recordLiveCacheSource(source:"local-cache"|"redis-cache"|"inflight"){currentProvider={queueMs:0,responseMs:0,source};}
export function recordLiveSse(durationMs:number){add("sseSendMs",durationMs);}
export function recordLiveRedis(durationMs:number){add("redisPublishMs",durationMs);}
export function completeLiveCycle(input:{processingMs:number;redisPublishMs:number;sseSendMs:number;fixtures:number;source?:string}){const internal=input.processingMs+input.redisPublishMs+input.sseSendMs;latest={completedAt:new Date().toISOString(),source:input.source??currentProvider.source,providerQueueMs:currentProvider.queueMs,providerResponseMs:currentProvider.responseMs,processingMs:input.processingMs,redisPublishMs:input.redisPublishMs,sseSendMs:input.sseSendMs,internalLatencyMs:internal,providerDelayMs:currentProvider.queueMs+currentProvider.responseMs,endToEndMeasuredMs:currentProvider.queueMs+currentProvider.responseMs+internal,fixtures:input.fixtures};add("processingMs",input.processingMs);add("internalLatencyMs",internal);add("providerDelayMs",latest.providerDelayMs);add("endToEndMeasuredMs",latest.endToEndMeasuredMs);}
function stats(name:string){const rows=stages.get(name)??[];const v=rows.map(x=>x.value).sort((a,b)=>a-b);const avg=v.length?v.reduce((a,b)=>a+b,0)/v.length:0;const p95=v.length?v[Math.min(v.length-1,Math.ceil(v.length*.95)-1)]:0;return{lastMs:Math.round((rows.at(-1)?.value??0)*10)/10,averageMs:Math.round(avg*10)/10,p95Ms:Math.round(p95*10)/10,samples:v.length};}
export function livePipelineSnapshot(){return{latest,stages:{providerQueue:stats("providerQueueMs"),providerResponse:stats("providerResponseMs"),processing:stats("processingMs"),redisPublish:stats("redisPublishMs"),sseSend:stats("sseSendMs"),internal:stats("internalLatencyMs"),providerDelay:stats("providerDelayMs"),endToEndMeasured:stats("endToEndMeasuredMs")},attribution:latest.providerDelayMs>latest.internalLatencyMs?"provider":"brainlive",note:"Il ritardo provider è misurato dalla coda all'arrivo della risposta API-Football; non rappresenta il tempo tra l'evento in campo e la disponibilità presso il provider."};}
export function resetLivePipelineTelemetryForTest(){stages.clear();currentProvider={queueMs:0,responseMs:0,source:"unknown"};}
